# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a736290b-0658-4b67-a305-64f2a02bdcb0'
  imageRepository: 'frontend-image'
  containerRegistry: 'mysharedacr1234.azurecr.io'
  tag: '1.0.0'
  imagePullSecret: 'mysharedacr12341458b525-auth'

  # Agent VM image name


stages:

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Default
    environment: 'CapStoneProjectAzure.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Build.SourcesDirectory)/manifests/deployment.yml
                $(Build.SourcesDirectory)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

