trigger: none

variables:
  azureSubscription: 'Your-Azure-Service-Connection'
  aksClusterName: 'aks-cluster-vnet2'
  aksResourceGroup: 'my-rg'
  helmChartName: 'backend-chart'
  helmChartRepo: './captest'
  helmChartVersion: '1.0.0'
  helmReleaseName: 'backend-app'
  helmNamespace: 'backend'

stages:
  - stage: HelmDeploy
    displayName: Deploy Helm Chart to AKS Cluster 2
    jobs:
      - job: Deploy
        pool:
          name: Default
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Helm Chart via Bicep'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Starting Helm chart deployment to AKS Cluster 2"

                az deployment group create \
                  --resource-group $(aksResourceGroup) \
                  --template-file helm-deploy.bicep \
                  --parameters \
                      aksName="$(aksClusterName)" \
                      aksResourceGroup="$(aksResourceGroup)" \
                      releaseName="$(helmReleaseName)" \
                      chartName="$(helmChartName)" \
                      chartVersion="$(helmChartVersion)" \
                      chartRepo="$(helmChartRepo)" \
                      chartValues="@./helm-values.yaml" \
                      namespace="$(helmNamespace)"
