trigger:
  branches:
    include:
      - main

variables:
  resourceGroup: 'my-rg'
  aksCluster: 'aks-cluster-vnet1'
  acrName: 'mysharedacr1234'
  bicepFile: 'BackendHelm.bicep'

pool:
  name: Default

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'prashanthscn'  # Replace with your Azure DevOps service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az bicep install
      az deployment group create \
        --resource-group $(resourceGroup) \
        --template-file $(bicepFile) \
        --parameters \
            aksClusterName=$(aksCluster) \
            aksResourceGroup=$(resourceGroup) \
            acrName=$(acrName) \
            chartName='myapp' \
            chartVersion='0.1.0' \
            namespace='default'
