trigger: none

variables:
  azureSubscription: 'prashanthscn'  # Name of your Azure DevOps service connection
  resourceGroup: 'my-rg'
  aksCluster: 'aks-cluster-vnet1'
  helmReleaseName: 'my-app'
  chartPath: './captest' # Path to your local Helm chart
  chartVersion: '1.0.0'

stages:
- stage: DeployHelmChart
  displayName: Deploy Helm chart to AKS
  jobs:
  - job: HelmDeploy
    displayName: Deploy via Helm
    pool:
      name: Default

    steps:
    - task: AzureCLI@2
      name: AKSLogin
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Getting AKS credentials..."
          az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster) --overwrite-existing

    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    - script: |
        echo "Packaging Helm chart..."
        helm lint $(chartPath)
        helm package $(chartPath) --version $(chartVersion) --destination .
      displayName: Helm Lint & Package

    - script: |
        echo "Creating namespace if not exists..."
        kubectl get namespace $(namespace) || kubectl create namespace $(namespace)

        echo "Installing/Upgrading Helm release..."
        helm upgrade --install $(helmReleaseName) ./$(helmReleaseName)-$(chartVersion).tgz \
          --namespace $(namespace) --create-namespace
      displayName: Helm Upgrade Install
