trigger: none

variables:
  azureSubscription: 'prashanthscn'
  aksClusterName1: 'aks-cluster-vnet1'
  aksClusterName2: 'aks-cluster-vnet2'
  aksResourceGroup: 'my-rg'
  helmChartName: 'backend-chart'
  helmChartRepo: 'oci://mysharedacr1234.azurecr.io/helm'
  helmChartVersion: '1.0.0'
  helmReleaseName: 'backend-app'
  helmNamespace: 'backend'

stages:
  - stage: HelmDeployAks1
    displayName: Deploy Helm Chart to AKS Cluster 1
    jobs:
      - job: DeployAks1
        displayName: Deploy to AKS 1
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy to AKS 1 via Bicep'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying Helm chart to AKS Cluster 1..."
                az deployment sub create \
                  --location eastus \
                  --template-file BackendDeploy.bicep \
                  --parameters \
                    aksName="$(aksClusterName1)" \
                    aksResourceGroup="$(aksResourceGroup)" \
                    releaseName="$(helmReleaseName)" \
                    chartName="$(helmChartName)" \
                    chartVersion="$(helmChartVersion)" \
                    chartRepo="$(helmChartRepo)" \
                    namespace="$(helmNamespace)"

  - stage: HelmDeployAks2
    displayName: Deploy Helm Chart to AKS Cluster 2
    jobs:
      - job: DeployAks2
        displayName: Deploy to AKS 2
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy to AKS 2 via Bicep'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying Helm chart to AKS Cluster 2..."
                az deployment sub create \
                  --location eastus \
                  --template-file BackendDeploy.bicep \
                  --parameters \
                    aksName="$(aksClusterName2)" \
                    aksResourceGroup="$(aksResourceGroup)" \
                    releaseName="$(helmReleaseName)" \
                    chartName="$(helmChartName)" \
                    chartVersion="$(helmChartVersion)" \
                    chartRepo="$(helmChartRepo)" \
                    namespace="$(helmNamespace)"
