trigger: none

variables:
  azureSubscription: 'prashanthscn'
  aksClusterName1: 'aks-cluster-vnet1'
  aksClusterName2: 'aks-cluster-vnet2'
  aksResourceGroup: 'my-rg'
  helmChartName: 'backend-chart'
  helmChartRepo: 'oci://mysharedacr1234.azurecr.io/helm'
  helmChartVersion: '1.0.0'
  helmReleaseName: 'backend-app'
  helmNamespace: 'backend'

stages:
  - stage: HelmDeployAk1
    displayName: Deploy Helm Chart to AKS Cluster 1
    jobs:
      - job: Deploy
        pool:
          name: Default
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Helm Chart via Bicep'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub create \
                  --location eastus \
                  --template-file BackendDeploy.bicep \
                  --parameters \
                    aksName="$(aksClusterName1)" \
                    aksResourceGroup="$(aksResourceGroup)" \
                    releaseName="$(helmReleaseName)" \
                    chartName="$(helmChartName)" \
                    chartVersion="$(helmChartVersion)" \
                    chartRepo="$(helmChartRepo)" \
                    namespace="$(helmNamespace)"




  - stage: HelmDeployAk2
    displayName: Deploy Helm Chart to AKS Cluster 2
    jobs:
      - job: Deploy
        pool:
          name: Default
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Helm Chart via Bicep'
            inputs:
              azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az deployment sub create \
                    --location eastus \
                    --template-file BackendDeploy.bicep \
                    --parameters \
                      aksName="$(aksClusterName1)" \
                      aksResourceGroup="$(aksResourceGroup)" \
                      releaseName="$(helmReleaseName)" \
                      chartName="$(helmChartName)" \
                      chartVersion="$(helmChartVersion)" \
                      chartRepo="$(helmChartRepo)" \
                      namespace="$(helmNamespace)"


