trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - task: AzureCLI@2
    displayName: 'Deploy Helm Chart via Bicep'
    inputs:
      azureSubscription: 'azure-service-connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group $(resourceGroupName) \
          --template-file ./bicep/main.bicep \
          --parameters \
              cluster1Name=$(cluster1Name) \
              cluster2Name=$(cluster2Name) \
              helmChartName=$(helmChartName) \
              helmChartVersion=$(helmChartVersion) \
              helmRepoUrl=$(helmRepoUrl) \
              namespace=$(namespace) \
              releaseName=$(releaseName)
    env:
      resourceGroupName: '$(resourceGroupName)'
      cluster1Name: 'aks-cluster1'
      cluster2Name: 'aks-cluster2'
      helmChartName: 'backend'
      helmChartVersion: '4.11.1'
      helmRepoUrl: 'oci://mysharedacr1234.azurecr.io/hel'
      namespace: 'default'
      releaseName: 'my-backend-release'