apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job
spec:
  template:
    spec:
      containers:
        - name: psql
          image: postgres:15
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Creating databases in Azure PostgreSQL...";
              for db in authentication_db bus_db carpool_db feedback_db notification_db payment_db route_db user_db; do
                echo "Creating database: $db"
                createdb \
                  --host=my-pgsql-server.postgres.database.azure.com \
                  --port=5432 \
                  --username=pgadmin@my-pgsql-server \
                  --dbname=postgres \
                  --sslmode=require \
                  $db || echo "Failed to create database: $db"
              done
          env:
            - name: PGPASSWORD
              value: "asdfghjklzxcvbnm@123"
      restartPolicy: OnFailure
