apiVersion: batch/v1
kind: Job
metadata:
  name: init-azure-postgres
spec:
  template:
    spec:
      containers:
        - name: psql
          image: postgres:15
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running init.sql against Azure PostgreSQL...";
              psql "host=my-pgsql-server.postgres.database.azure.com \
                    port=5432 \
                    dbname=postgres \
                    user=pgadmin@my-pgsql-server \
                    password='asdfghjklzxcvbnm@123' \
                    sslmode=require" \
              -f /scripts/init.sql
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: init-script
          configMap:
            name: azure-postgres-init
