appVersion: "latest-v2"

images:
  - name: api-gateway
    image: mysharedacr1234.azurecr.io/api-gateway:1.1.0
    port: 9000

  - name: authentication-service
    image: mysharedacr1234.azurecr.io/authentication-service:1.1.1
    port: 9089
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/authentication_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: bus-service
    image: mysharedacr1234.azurecr.io/bus-service-pipeline:1.1.0
    port: 9095
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/bus_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: carpool-service
    image: mysharedacr1234.azurecr.io/carpool-service:1.1.0
    port: 9096
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/carpool_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: feedback-service
    image: mysharedacr1234.azurecr.io/feedback-service:1.1.0
    port: 9099
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/feedback_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: notification-service
    image: mysharedacr1234.azurecr.io/notification-service:1.1.0
    port: 9092
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/notification_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: payment-service
    image: mysharedacr1234.azurecr.io/payment-service:1.1.0
    port: 9696
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/payment_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: route-service
    image: mysharedacr1234.azurecr.io/route-service:1.1.0
    port: 9097
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/route_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

  - name: service-registry
    image: mysharedacr1234.azurecr.io/service-registry:1.1.0
    port: 8761

  - name: user-service
    image: mysharedacr1234.azurecr.io/user-service:1.1.0
    port: 9098
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/user_db?sslmode=require
      - name: SPRING_DATASOURCE_USERNAME
        value: pgadmin
      - name: SPRING_DATASOURCE_PASSWORD
        value: asdfghjklzxcvbnm@123

initdbScript: |
  CREATE DATABASE authentication_db;
  CREATE DATABASE bus_db;
  CREATE DATABASE carpool_db;
  CREATE DATABASE feedback_db;
  CREATE DATABASE notification_db;
  CREATE DATABASE payment_db;
  CREATE DATABASE route_db;
  CREATE DATABASE user_db;



# appVersion: "latest-v2"
# images:
#   - name: api-gateway
#     image: mysharedacr1234.azurecr.io/api-gateway:1.1.0
#     port: 9000

#   - name: authentication-service
#     image: mysharedacr1234.azurecr.io/authentication-service:1.1.0
#     port: 9089
#     database: authentication_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/authentication_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: bus-service
#     image: mysharedacr1234.azurecr.io/bus-service:1.1.0
#     port: 9095
#     database: bus_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/bus_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: carpool-service
#     image: mysharedacr1234.azurecr.io/carpool-service:1.1.0
#     port: 9096
#     database: carpool_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/carpool_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: feedback-service
#     image: mysharedacr1234.azurecr.io/feedback-service:1.1.0
#     port: 9099
#     database: feedback_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/feedback_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: notification-service
#     image: mysharedacr1234.azurecr.io/notification-service:1.1.0
#     port: 9092
#     database: notification_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/notification_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: payment-service
#     image: mysharedacr1234.azurecr.io/payment-service:1.1.0
#     port: 9696
#     database: payment_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/payment_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: route-service
#     image: mysharedacr1234.azurecr.io/route-service:1.1.0
#     port: 9097
#     database: route_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/route_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

#   - name: service-registry
#     image: mysharedacr1234.azurecr.io/service-registry:1.1.0
#     port: 8761

#   - name: user-service
#     image: mysharedacr1234.azurecr.io/user-service:1.1.0
#     port: 9098
#     database: user_db
#     env:
#       - name: SPRING_DATASOURCE_URL
#         value: jdbc:postgresql://my-pgsql-server.postgres.database.azure.com:5432/user_db
#       - name: SPRING_DATASOURCE_USERNAME
#         value: pgadmin
#       - name: SPRING_DATASOURCE_PASSWORD
#         value: asdfghjklzxcvbnm@123

# initdbScript: |
#   CREATE DATABASE authentication_db;
#   CREATE DATABASE bus_db;
#   CREATE DATABASE carpool_db;
#   CREATE DATABASE feedback_db;
#   CREATE DATABASE notification_db;
#   CREATE DATABASE payment_db;
#   CREATE DATABASE route_db;
#   CREATE DATABASE user_db;

# ingress:
#   enabled: true
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   hosts:
#     - host: example.com
#       paths:
#         - path: /auth(/|$)(.*)
#           serviceName: auth-service
#           servicePort: 9089
#         - path: /buses(/|$)(.*)
#           serviceName: bus-service
#           servicePort: 9095
#         - path: /busSchedules(/|$)(.*)
#           serviceName: bus-schedule-service
#           servicePort: 9095
#         - path: /routes(/|$)(.*)
#           serviceName: route-service
#           servicePort: 9097
#         - path: /carpools(/|$)(.*)
#           serviceName: carpool-service
#           servicePort: 9096
#         - path: /feedback(/|$)(.*)
#           serviceName: feedback-service
#           servicePort: 9099
#         - path: /notifications(/|$)(.*)
#           serviceName: notification-service
#           servicePort: 9092
#         - path: /payment(/|$)(.*)
#           serviceName: payment-service
#           servicePort: 9696
#         - path: /stops(/|$)(.*)
#           serviceName: stop-service
#           servicePort: 9097
#         - path: /tickets(/|$)(.*)
#           serviceName: ticket-service
#           servicePort: 8080
#         - path: /users(/|$)(.*)
#           serviceName: user-service
#           servicePort: 9098
#         - path: /realtime(/|$)(.*)
#           serviceName: realtime-data-service
#           servicePort: 9095

