trigger: none

variables:
  dockerRegistryServiceConnection: 'b0e254bb-b547-4604-a227-4bf606715cf8'
  imageRepository: 'api-gateway'
  containerRegistry: 'mysharedacr1234.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Backend/api-gateway/Dockerfile'
  tag: '1.0.0'
  workingDirectory: '$(Build.SourcesDirectory)/Backend/api-gateway'

stages:
- stage: Build
  displayName: CI build And Test Integration
  jobs:
  - job: BuildAndPush
    displayName: Install Java & Maven → Build → Dockerize → Push
    pool:
      name: Default
      
    steps:
    - checkout: self

    - script: |
        echo "Installing Java 17..."
        sudo apt-get update -y
        sudo apt-get install -y openjdk-17-jdk
        java -version

        echo "Installing Maven..."
        sudo apt-get install -y maven
        mvn -version
      displayName: 'Install Java 17 and Maven'

    - script: |
        echo "Running Maven Build..."
        cd $(workingDirectory)
        mvn clean package
      displayName: 'Installing Maven'
    

    
    - task: PublishBuildArtifacts@1
      displayName: Publishing the artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'api-gateway'
        publishLocation: 'Container'


- stage: ArtifactBuild
  displayName: Build and Push Stage
  jobs:
  - job: BuildAndPush
    displayName: Building and Push Stage to Acr
    pool:
      name: Default
      
    steps:
    - checkout: self
    - task: Docker@2
      displayName: 'Build and Push Docker Image to ACR'
      inputs:
        command: 'buildAndPush'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
