trigger: none

variables:
  dockerRegistryServiceConnection: 'b0e254bb-b547-4604-a227-4bf606715cf8'
  imageRepository: 'api-gateway'
  containerRegistry: 'mysharedacr1234.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Backend/api-gateway/Dockerfile'
  tag: '1.0.0'
  workingDirectory: '$(Build.SourcesDirectory)/Backend/api-gateway'

stages:
- stage: Build
  displayName: CI build And Test Integration
  jobs:
  - job: BuildAndPush
    displayName: Install Java & Maven → Build → Dockerize → Push
    pool:
      name: Default
      
    steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        echo "Installing Java 17..."
        sudo apt-get update -y
        sudo apt-get install -y openjdk-17-jdk
        java -version

        echo "Installing Maven..."
        sudo apt-get install -y maven
        mvn -version
      displayName: 'Install Java 17 and Maven'

    - script: |
        echo "Running Maven Build..."
        cd $(workingDirectory)
        mvn clean package
      displayName: 'Installing Maven'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'api-gateway'
        publishLocation: 'pipeline'
    - task: SonarCloudPrepare@3
      inputs:
        SonarQube: 'sonar'
        organization: 'devuser09'
        scannerMode: 'other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=devuser09_CapStone-Project-Azure
          sonar.projectName=CapStone-Project-Azure


- stage: ArtifactBuild
  displayName: Build and Push Stage
  jobs:
  - job: BuildAndPush
    displayName: Building and Push Stage to Acr
    pool:
      name: Default
      
    steps:
    - checkout: self
    - task: Docker@2
      displayName: 'Build and Push Docker Image to ACR'
      inputs:
        command: 'buildAndPush'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
