trigger: none

variables:
  dockerRegistryServiceConnection: 'b0e254bb-b547-4604-a227-4bf606715cf8'
  imageRepository: 'api-gateway'
  containerRegistry: 'mysharedacr1234.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Backend/api-gateway/Dockerfile'
  tag: '1.0.0'
  workingDirectory: '$(Build.SourcesDirectory)/Backend/api-gateway'

stages:
- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: BuildAndPush
    displayName: Install Java & Maven → Build → Dockerize → Push
    pool:
      name: Default
      
    steps:
    - checkout: self

    - script: |
        echo "Installing Java 11..."
        sudo apt-get update -y
        sudo apt-get install -y openjdk-11-jre-headless
        java -version

        echo "Installing Maven..."
        sudo apt-get install -y maven
        mvn -version
      displayName: 'Install Java 11 and Maven'

    - script: |
        echo "Running Maven Build..."
        cd $(workingDirectory)
        mvn clean package
      displayName: 'Build and Test with Maven'

    - task: Docker@2
      displayName: 'Build and Push Docker Image to ACR'
      inputs:
        command: 'buildAndPush'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
